Enhance error handling in lockfile sync check to ensure workflow fails if package-lock.json is out of sync

diff --git a/.github/workflows/check-pull-request.yml b/.github/workflows/check-pull-request.yml
--- a/.github/workflows/check-pull-request.yml
+++ b/.github/workflows/check-pull-request.yml
@@ -27,7 +27,8 @@ jobs:
 
       - name: Check lockfile sync
         run: |
-          npm install --package-lock-only && git diff --exit-code package-lock.json || echo "ERROR: You need to run npm install and commit package-lock.json"
+          npm install --package-lock-only && git diff --exit-code package-lock.json || \
+          echo "ERROR: You need to run npm install and commit package-lock.json" && exit 1
 
   test:
     name: Test and Lint
