Enhance Docker image testing in CI workflow
- Updated the Docker image build step to include running the container and checking its health status.
- Implemented a retry mechanism to wait for the container to become healthy before proceeding.
- Adjusted the Snyk test step to skip for dependabot commits.

diff --git a/.github/workflows/check-pull-request.yml b/.github/workflows/check-pull-request.yml
--- a/.github/workflows/check-pull-request.yml
+++ b/.github/workflows/check-pull-request.yml
@@ -31,13 +31,32 @@ jobs:
           npm run lint
           npm test
 
-      - name: Test Docker Image Build
+      - name: Test Docker Image Build and Run
         run: |
-          set +e
-          docker build --no-cache --tag cdp-node-frontend-template .
-          exit $?
+          set -e
+          docker build --no-cache --tag grants-ui-build-test .
+          CONTAINER_ID=$(docker run --rm -d -p 3000:3000 -e SESSION_CACHE_ENGINE=memory grants-ui-build-test)
+          echo "Container ID: $CONTAINER_ID"
+          ATTEMPTS=0
+          MAX_ATTEMPTS=15
+          echo "Waiting for container to be healthy..."
+          until $(curl --output /dev/null --silent --head --fail http://localhost:3000/health); do
+              if [ ${ATTEMPTS} -eq ${MAX_ATTEMPTS} ]; then
+                  echo "Error: Timed out waiting for container to be healthy."
+                  echo "--- Container Logs ---"
+                  docker logs $CONTAINER_ID
+                  docker stop $CONTAINER_ID > /dev/null
+                  exit 1
+              fi
+              printf '.'
+              ATTEMPTS=$(($ATTEMPTS+1))
+              sleep 2
+          done
+          echo -e "\nContainer is healthy!"
+          docker stop $CONTAINER_ID > /dev/null
 
       - name: Run Snyk test
+        if: github.actor != 'dependabot[bot]'
         uses: snyk/actions/node@master
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
