Enhance lockfile sync check in PR workflow to provide clearer error message if package-lock.json is out of sync

diff --git a/.github/workflows/check-pull-request.yml b/.github/workflows/check-pull-request.yml
--- a/.github/workflows/check-pull-request.yml
+++ b/.github/workflows/check-pull-request.yml
@@ -26,7 +26,8 @@ jobs:
           cache: npm
 
       - name: Check lockfile sync
-        run: npm install --package-lock-only && git diff --exit-code package-lock.json
+        run: |
+          npm install --package-lock-only && git diff --exit-code package-lock.json || echo "ERROR: You need to run npm install and commit package-lock.json"
 
   test:
     name: Test and Lint
